---
# worker.yaml
apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  namespace: airflow
spec:
  clusterIP: None
  ports:
  - port: 8793
    name: worker
  selector:
    app: airflow-worker