---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key-secrets
  namespace: airflow
type: Opaque
data:
  # Clave Fernet para cifrar conexiones y contraseñas
  AIRFLOW__CORE__FERNET_KEY: "WlVHeUE2X0xJWlpHUEhqemI3eTZRc0EyM0EzMVdkM0gxd2x6emg2SVdWND0K"