apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  # Executor
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags

  # Auth Manager (FAB)
  AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
  _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-fab

  # DAG Processor (Airflow 3.x)
  AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL: "30"        # reemplaza DAG_DIR_LIST_INTERVAL
  AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "10"  # cada 10s procesar DAGs
  AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: "True"

  # StatsD metrics
  AIRFLOW__METRICS__STATSD_ON: "True"
  AIRFLOW__METRICS__STATSD_HOST: airflow-statsd
  AIRFLOW__METRICS__STATSD_PORT: "9125"

  # API and Webserver
  AIRFLOW__API__ENABLE_EXPERIMENTAL_API: "False"
  AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  AIRFLOW__API__URL: "http://airflow-api-server.airflow.svc.cluster.local:8080"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__WEBSERVER__RBAC: "True"

  # Security keys
  AIRFLOW__CORE__FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
  AIRFLOW__CORE__INTERNAL_API_URL: "http://airflow-api-server:8080"
  AIRFLOW__CORE__ENABLE_INTERNAL_API: "True"
  AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: 74b90d6d2284468b6c6d144c24a107154ccd8ccaab130589637c6a5908266389

  # Triggerer
  AIRFLOW__TRIGGERER__DEFAULT_CAPACITY: "1000"

  # Logging
  AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: ""

  # Database connection
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow

  # Component health check ports
  AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_SERVER_PORT: "8794"
  AIRFLOW__TRIGGERER__TRIGGERER_HEALTH_CHECK_SERVER_PORT: "8795"
  AIRFLOW__WORKERS__WORKER_LOG_SERVER_PORT: "8793"
  AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_SERVER_HOST: "0.0.0.0"
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "True"

  # API Basic Auth credentials
  AIRFLOW__API__BASIC_AUTH_USER: "airflow"
  AIRFLOW__API__BASIC_AUTH_PASSWORD: "La.Password.$egura"
