---
# init-db-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-run-airflow-migrations
  namespace: airflow
spec:
  template:
    metadata:
      labels:
        app: airflow-run-airflow-migrations
    spec:
      serviceAccountName: airflow
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-db
        image: postgres:13
        command:
        - sh
        - -c
        - |
          until pg_isready -h airflow-postgresql -U airflow; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
      containers:
      - name: run-migrations
        image: apache/airflow:3.1.0
        command: 
        - bash
        - -c
        - |
          echo "=== Installing FAB provider ==="
          pip install --no-cache-dir apache-airflow-providers-fab
          
          echo "=== Configuring FAB Auth Manager ==="
          export AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
          
          echo "=== Running DB migration ==="
          airflow db migrate
          
          echo "=== Creating admin user ==="
          airflow users create \
            --username admin \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email admin@example.com \
            --password admin || echo "User already exists"
          
          echo "=== Migration job completed successfully ==="
        env:
        - name: AIRFLOW__CORE__AUTH_MANAGER
          value: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-postgres-secrets