apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  serviceName: airflow-redis
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
  template:
    metadata:
      labels:
        app: airflow-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:  
        - "sh"
        - "-c"
        - |
          redis-server \
          --appendonly yes \
          --requirepass $(REDIS_PASSWORD) \
          --protected-mode no \
          --bind 0.0.0.0
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-redis-password
              key: redis-password
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "redis-cli -a $REDIS_PASSWORD ping | grep PONG"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "redis-cli -a $REDIS_PASSWORD ping | grep PONG"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc