apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-statsd
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-statsd
  template:
    metadata:
      labels:
        app: airflow-statsd
    spec:
      containers:
      - name: statsd
        image: quay.io/prometheus/statsd-exporter:v0.26.0
        args:
        - --statsd.mapping-config=/etc/statsd/mappings.yml
        ports:
        - containerPort: 9125
          protocol: UDP
          name: statsd
        - containerPort: 9102
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: statsd-config
          mountPath: /etc/statsd
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: statsd-config
        configMap:
          name: airflow-statsd-config